### ISSUE TITLE
x-y coordinates: projection information missing.

### ISSUE THREAD

**Issue by lejeunemax** [IEAWindTask37/windIO#101]
The current ```coordinate``` definition does not specify any information about the projection used for obtaining the West-East ad South-North coordinate. Though of minor inconvenience when dealing with individual wind farms, it can become the source of error for larger-scale runs (ie: meso-scale) including many wind farms. 

While allowing for lat/lon input may not be the best option, I believe including some information about the projection used would be very useful. 
One simple way to do this could be to add an optional "projection" field described as a PROJ string (eg: `proj +proj=merc +lat_ts=56.5 +ellps=GRS80`)

I was additionally wondering if adding an optional z coordinate would make sense or if it was considered redundant with the altitude field of the site schema.

```
definitions:
  coordinate:
    title: Coordinate
    description: Point coordinate
    type: object
    required:
      - x
      - y
    additionalProperties: false
    properties:
      x:
        title: X coordinate
        description: West-East coordinate
        type: number
        units: m
      y:
        title: Y coordinate
        description: South-North coordinate
        type: number
        units: m
     proj:
        title: Projection
        description: PROJ string describing the projection used to obtain the x and y coordinates.
        type: str
```
