### ISSUE TITLE
Split Turbine schema into multiple schemas

### ISSUE THREAD

**Issue by kenloen** [IEAWindTask37/windIO#31]
The current Turbine schema is currently a single schema but it might be better to split the schema into multiple schemas to for example enable having a definition of the rotor combined both a tower and monopile or a tower and floater design. Other ways of combining different parts of the definition could also be interesting. 

Any thought on how this could and should be done is most welcome.

**Comment by ptrbortolotti** [comment]
This is a good idea, but might become tricky to handle. Do we have a good way to built a schema assembling sub-schemas? And similarly, do we have a way to build a yaml assembling sub-yamls? @rafmudaf @kilojoules @kenloen

**Comment by ptrbortolotti** [comment]
Is the discussion in PR #74 relevant here?

**Comment by kenloen** [comment]
The thinks about manageing schemas are described here: https://json-schema.org/understanding-json-schema/structuring

We would need to add an `$id` that points to the location of be base schema and then use `$ref` to point to the sub schema. 

I am not completely sure if the `$id: https://raw.githubusercontent.com/IEAWindTask37/windIO/refs/heads/main/windIO/turbine/IEAontology_schema` (maybe we should change the base name to `turbine` or something similar). But I will try and see if that works. I am not sure if this will work for schemas defined in YAML or that will only work for JSON. An option from this would be to "serve" the schemas as JSON, meaning that every time we build them we convert them to JSON and host them as a part of the documentation with a URI like: `https://windio.readthedocs.io/schemas/turbine.schema.json`
Or with could switch to using json for the schemas - we can still use YAML for defining the models in that case.

**Comment by kenloen** [comment]
I have been thinking about the issues of the schema having to serve different needs and that different tools would require different entries to be present - hence there will not be a unique set of required entries for a windIO turbine. Fx. the turbine model for wind farm evaluation would only require a small subset of what would be required for an aeroelastic evaluation of a turbine. 

I would therefore suggest a slightly different approach as to what we do now. 

Instead of only having *a* turbine schema, with could have *a* turbine schema that defines *all* possible entries for a turbine but it do *not requrie* any entry. Then we will use this base schema  to create spesefic schemes where the entries are required. In that way we could say that this instance of the schema is a *"windIO wind-farm turbine"* or a *"windIO aero-elastic turbine"*, 

Below I have tried to make  a mock up of how this would look. 

File structure
```
plant
|- common.yaml
|- energy_resource.yaml
|- ...
turbine
|- turbine_base.yaml
|- turbine_wind_farm.yaml
|- turbine_aero_elastic.yaml
|-  ...
|- assembly.yaml
|- components
      |- blade.yaml
      |- hub.yaml
|- control
      |- ...
|- performance.yaml
common
|- sub_schemas
      |- grid_value.yaml
      |- ...
|- airfoils
      |- ...
|- materials
      |- ...
|- ...
```

Where the turbine files are.
`turbine_base.yaml`:
```yaml
$schema: "http://json-schema.org/draft-07/schema#"
$id: https://raw.githubusercontent.com/IEAWindSystems/windIO/refs/heads/main/windIO/schemas/turbine/turbine_base
title: windIO Base turbine
type: object
properties:
    assembly:
       $ref: /assembly
    components:
       type: object
       properties:
              blade: {$ref: /components/blade}
              hub: {$ref: /components/hub}
       ...
    performance: {$ref: /performance}
    ...
```

`turbine_wind_farm.yaml`:
```yaml
$schema: "http://json-schema.org/draft-07/schema#"
$id: https://raw.githubusercontent.com/IEAWindSystems/windIO/refs/heads/main/windIO/schemas/turbine/turbine_base
$ref: turbine_base
title: windIO wind farm turbine
required:
    - performance
```

`turbine_aero_elastic.yaml`:
```yaml
$schema: "http://json-schema.org/draft-07/schema#"
$id: https://raw.githubusercontent.com/IEAWindSystems/windIO/refs/heads/main/windIO/schemas/turbine/turbine_base
$ref: turbine_base
title: windIO aero-elastic turbine
required:
    - components
    -  control
    - ...
properties:
    components:
       required:
          - blade
          - hub
          - ...
```
Any thoughts?
