### ISSUE TITLE
Update internal_structure_2d_fem

### ISSUE THREAD

**Issue by fzahle** [IEAWindTask37/windIO#96]
The blade internal structural definition is gaining traction and is used across quite a few tools. We have had several discussions on various needed improvements of its definition, but not discussed the possibility of larger changes that address the various shortcomings we've each identified over the years of using it. So this issue is an attempt to note down my own thoughts on this and collect feedback from the rest of the working group and other users of the `internal_structure_2d_fem` section. For context please also see #93 that contains a suggestion for reorganising the rest of the ´blade` section.

## Name
`internal_structure_2d_fem` is increasingly being used for higher fidelity tools so perhaps it's time to remove `_2d_fem`? There isn't really any need to limit the definition to 2D since a 2D model can be just as detailed and complex as a 3D model. And we know it's already being used to construct 3D FE models.

## Reference axis
As for `elastic_properties_mb` I would suggest to remove `reference_axis` and enforce a single truth that lives in the `blade.geometry` section.

## Anchors instead of individual layer start_nd_arc/end_nd_arc

We currently define the spanwise and chordwise extent for each layer based on `start_nd_arc` and `end_nd_arc`. Each layer has to define these quantities explicitly or can be anchored to other layers or existing anchors such as LE or TE or with `offset_y_pa` which is an offset relative to the `reference_axis`.

Instead of each layer specifying chordwise extent along with spanwise start/stop through its `grid`, this could be simplified to only allow references to anchors. Motivations for this change:

* Often layers share start/end in the chordwise direction,
* Anchors can be used as intermediate curves that don't necessarily define a layer's start/end, but some other meaningful geometric reference.
* Anchoring one layer to another requires that the anchored layer's spanwise extent is equal to or greater than the layer in question.
* Currently, anchoring one layer to another doesn't allow for the two layers to be overlapping, ie anchoring layer2's start_nd_arc to layer2' start_nd_arc.
* Dividing the blade into "regions", optionally along the entire span, makes it easier to make simple block-structured shell meshes, while still allowing to specify layers spanning across several of these regions.
* We could consider differentiating between anchors used to define start/end of layers and anchors (helper curves) used for relative placement of other anchors.

Examples:

* An anchor curve for the TE reinforcement could extend across e.g. grid [0.02, 0.98], and while TE UD reinforcement extends from [0.05, 0.95], another layer can reference the same anchor for its full extent. Currently, to get around this issue we'd have to set thickness of the given layer to zero beyond its intended extent.
* A carbon UD pultrusion is transitioned into glass UD in the blade tip, and should have same width.

The proposed change would thus introduce a new section called `anchors` in the `internal_structure` section. It is in a sense a hybrid between a layer-based and region based approach, still easily allowing an all-over layer such as skin or coating.

It could be useful to allow for several types of anchor arcs, curves or planes. we now define the following: `reference_axis` (required, explicit definition, which in all current RWTs is identical to the axis defined in `outer_shape_bem`), `TE` and `LE` (can be referenced, but isn't explicitly defined) and then `offset_y_pa`. The definition of the leading edge is ambiguous since this could be the furthest point from the TE or simply min(y) in the local chord reference frame. In the root the desired "leading edge" is also not necessarily the one that follows the aerodynamic twist and leading edge, but one that follows the mold split, which could be different. The trailing edge is currently defined as the midpoint between the first and last point of the cross-section, but this isn't very intuitive for placing layers, since depending on the TE topology a layer could wrap around the TE or stop at the edge on either suction or pressure side. So to add flexibility and less ambiguity we could define the helper arc curves explicitly with name tags. could be named `anchors`. Anchor types will look a lot like what we're used to from layers, but also define new types.

Types of anchors could be:

* nd_arc: non-dimensional arc position, which could be the LE, TEss etc: 

```yaml
type: nd_arc_position
name: LE
grid: []
values: []
```

Anchors referencing other anchors:

```yaml
type: nd_arc_position
name: TEreinf
anchor: "TE"
grid: [0.02, 0.05, 0.95, 0.98]
width: [0.05, 0.4, 0.4, 0.05]
side: suction
```

* curve: user-defined curve with the same format as `reference_axis`. `reference_axis` should still be possible to reference without having to define it here.

* plane: we could opt for a completely generic method for defining planes, but we have in our own tools worked with two specific ways to specify reference planes:
  1) * based on the lofted surface including prebend and geometric twist, rotate the blade by a given amount in the blade root system.
     * create a vertical plane spanning two points on the reference axis.
  2) * based on the lofted surface including prebend and geometric twist, rotate the blade by a given amount in the blade root system.
     * create a vertical curved plane that follows a reference curve y-z
     * offset the plane in the normal direction to the plane and intersect the surface.

~~Layers can then define a given quantity to have an `offset` to the plane in the normal direction to the plane. This offset plane is then intersected with the surface.~~

The first method is needed to make straight or linearly tapered spar caps, while the second method allows to place curved layers that follow a reference curve's y-z coordinates. This could be to place a shear web at a given distance from the trailing edge. To allow for this, we need the possibility of more anchor curves than just the reference axis.

```yaml
    offset_plane_and_width:
        name: spar_cap_ss
        anchor: reference_axis
        side: suction
        blade_rotation: 8.
        offset:
          grid: [0.05, 0.95]
          values: [0.04, 0.0]
        reference_axis_bounds: [0.0, 0.98]
        width:
          grid: [0.05, 0.95]
          values: [0.8, 0.8]
```

To allow for easy specification of spar cap center+width we define such an anchor to implictly result in two intersections, and to reference these two intersections, the naming convention would be `spar_cap_ss_start` and `spar_cap_ss_end`.

```yaml
    offset_plane:
        name: fore_web
        anchor: reference_axis
        blade_rotation: 8.
        offset:
          grid: [0.05, 0.95]
          values: [0.35, 0.35]
        reference_axis_bounds: [0.0, 0.98]
```

```yaml
    offset_curve:
        name: spar_cap_center
        anchor: reference_axis
        blade_rotation: 8.
        reference_axis_bounds: [0.0, 0.98]
```

Note: Specifying zero rotation for `offset_plane` corresponds to `offset_y_pa` with rotation  equal to the blade twist. If `offset_y_pa` is defined with a rotation array not equal to twist, the intersection with the surface will not result in a straight line (or plane in the case of webs) since rotation is defined carried out in the local chord reference frame around the reference axis.

In the above exaample anchors, `start_nd_arc` and `end_nd_arc` are not necessarily defined, but we should consider making the explicit grid/values definition of `start_nd_arc` and `end_nd_arc` required, so all tools can *always* reproduce a layup from this. Tools that don't have any of the guide curve/plane intersection methods can then be guaranteed to read a windIO file. In our tools we first check if an arc position can be computed from a derived quantity and as the last step use grid/value directly if nothing else has been specified.

## Layer spanwise and chordwise extent
Layers will now define their chordwise extent entirely from what used to be the "fixed" definition, cross-referencing named anchors for their start/end arc position.

A spanwise `grid` defined for individual array quantities such as thickness is convenient since one can manually specify constant/linear variation with few entries, or complex variation with a fine grained grid. However, using `grid` to define a layer's spanwise extent is limiting, since in an optimization, we could be interested in finding the optimal spanwise extent of a spar cap, just as we could want to optimize the chordwise location.

So we could extend the thinking of `*_nd_arc` used in the chordwise direction to the spanwise direction, implying a floating point value for a layer's start and end spanwise direction. When going to this definition, the `grid` for e.g. thickness should then be non-dimensional within the local extent of the layer and not the "global" blade grid.

Combining all these changes we get:

```yaml
name: te_filler_ss
material: foam
start_nd_span: 0.1
end_nd_span: 0.9
start_nd_arc:
  anchor: te_reinforcement_ss
end_nd_arc:
  anchor: spar_cap_ss_start
thickness:
  grid: [0., 0.02, 0.98, 1.0]
  values: [0.001, 0.04, 0.04, 0.001]
```

## Layer thickness and fiber_orientation

We've discussed that it could be useful to support layer thickness to be defined on a 2D non-dimensional grid, which would for example allow for specifying taper of core material, but also more exotic layups based on e.g. additive manufacturing. A challenge currently is that taper is left to the individual analysis tool, resulting in variations in predicted stiffness. Besides tapering of core at the TE, another example could be how SONATA rounds the edges of e.g. the spar cap, which is not what our tools do. Since windIO doesn't specify anything, either approach could be "the right one".

Update: To be consistent with the above proposal of not using `grid` to define spanwise extent, `u-v` grid should be in range [0:1].

```yaml
thickness:
  grid2d:
    u: # spanwise grid
      - [0.0, 0.5, 1.0]
      - [0.0, 0.5, 1.0]
      - [0.0, 0.5, 1.0]
    v: # chordwise grid
      - [0.00 0.0, 0.0]
      - [0.1, 0.1, 0.1]
      - [0.9, 0.9, 0.9]
      - [1.0, 1.0, 1.0]
  values2d:
    - [0.0001, 0.0001, 0.0001]
    - [0.03, 0.03, 0.03]
    - [0.03, 0.03, 0.03]
    - [0.0001, 0.0001, 0.0001]
```

For tools that don't support tapered layers, we could define the convention that the maximum value of thickness in the `v` direction should be used.

Update:
Alternative proposed by @peter-greaves where the first line is the spanwise grid and following lines define the chordwise grid:
```yaml
thickness:
  grid:
    - [0, 0.25, 0.75, 1]
    - [0.05, 0.05, 0.05, 0.05]
    - [0.1, 0.1, 0.1, 0.1]
    - [0.3, 0.3, 0.3, 0.3]
    - [0.35, 0.35, 0.35,0.35]
  values:
    - [0.0, 0.0, 0.0, 0.0]
    - [0.05, 0.05, 0.05, 0.05]
    - [0.05, 0.05, 0.05, 0.05]
    - [0.0, 0.0, 0.0,0.0]
```

Peter's suggestion could likewise be modified so that spanwise/chordwise grids are normalised to [0:1] and their physical extent defined with `start/end_nd_span` and anchor curves.

## Shear webs

* Shear webs are assumed to connect the two shells as straight lines, which is normally the case. Allowing to specify a surface that could be curved would allow for any shape, but should we then only support specific types of shapes that can be described parametrically?
* Layers in webs are currently assumed to cover the entire shear web, which is not the case for core material, but could also be the case for other layers. this can easily be addressed by adding a `start_nd_arc` and `end_nd_arc` to web layers, which then refers not to the blade surface but non-dimensional distance along the web arc.
* Update: Shear webs do not define how thickness should be offset from the plane connecting the two shells. Centered, toward LE or TE. A field needs to be added with this information.

## Bond lines, trailing edge topology, web flanges etc

The detail level of the structural definition was purposely quite simplified, but we can see that structural modellers are interested in the schema, and we should attempt to address specification of more geometrically complex features. I don't have a lot of specific suggestions for these features, so we need input from experienced modellers to guide us what's feasible to include in a schema that should probably still be viewed as a schema for conceptual design. But it could be interesting to discuss how far we can get without developing a fully fledged CAD-like definition.

Update: proposed definition of web flanges and bondlines:

```yaml
webs:
  - name: fore_web
    ...<anchor references>
    flanges:
      - type: L
        side: suction
        bondline:
          material: glue
          thickness:
            grid: [0., 0.5, 1.0]
            values: [0.03, 0.02, 0.01]
        start_nd_arc: fore_web_anchor
        end_nd_arc: fore_web_flange_anchor_ss
      - type: L
        side: pressure
        bondline:
          material: glue
          thickness:
            grid: [0., 0.5, 1.0]
            values: [0.03, 0.02, 0.01]
        start_nd_arc: fore_web_anchor
        end_nd_arc: fore_web_flange_anchor_ps
```

## Added mass

@jelmer-cnossen proposed to include the possibility to apply 'added mass' in the structure definition in order to account for non-load carrying components like root inserts, lightning protection, de-icing systems etc.

## Overall comments

If we implement any of the above suggestions, it's important that we don't make use of the schema with our current go-to tools such as PreComp, Sonata, BECAS more cumbersome just to support higher fidelity geometric detail and higher fidelity tools. But I think many of the above suggestions lie within our current tools' capabilities and simply represent improvements of the windIO structural parameterization that we could all benefit from.

Some suggestions in particular the 2D thickness grid, bond lines, shear web variable thickness potentially require updates to the underlying FE meshers, but chances are that meshers support these features already.

I will try to update this text with whatever input we get.
